Update docker-build-and-run-test.yml

diff --git a/.github/workflows/docker-build-and-run-test.yml b/.github/workflows/docker-build-and-run-test.yml
--- a/.github/workflows/docker-build-and-run-test.yml
+++ b/.github/workflows/docker-build-and-run-test.yml
@@ -38,17 +38,17 @@ jobs:
       # Step 5: Run the container (to check if it runs correctly)
       - name: Run Docker container
         run: |
-          docker run -d -p 8000:8000 -p 8501:8501 reallocate-dashboard
+          docker run -d --name dashboard-container -p 8000:8000 -p 8501:8501 reallocate-dashboard
      
       - name: Capture Docker container logs if health check fails
         run: |
-          docker logs my-running-container || echo "Failed to capture logs"
+          docker logs dashboard-container || echo "Failed to capture logs"
 
 
       # Step 6: Test the running container (Optional step for health check or functionality test)
       - name: Test the running container
         run: |
-          curl --fail http://localhost:8501 || exit 1
+          docker exec dashboard-container curl --fail http://localhost:8501 || exit 1
       
  
       # Step 7: Stop the Docker container after tests
